trigger:
  branches:
    include: 
    - develop
    - master
  paths:
    include: 
     - /src/*

resources:
  repositories:
  - repository: devops
    type: git
    name: pub/devops
    ref: feature/add_npm_builddeploy_script


jobs:
- template: npm-build-deploy.yml@devops
  parameters:
    packageName: 'npm-test-app'
    hasUnitTests: true
    createPackage: true
    createGithubRelease: false